### ISSUE TITLE
Locked variable not setting

### ISSUE THREAD

**Issue by snalye** [qbcore-framework/qb-doorlock#73]
When using /newdoor and checking locked, it does not produce the locked variable in the configuration files. 
![image](https://user-images.githubusercontent.com/1113196/154825048-bdd05565-ace1-4c10-b760-e183439051a4.png)
![image](https://user-images.githubusercontent.com/1113196/154825072-71235600-2f98-4c2f-ad4e-9a4c067b12df.png)

**Comment by snalye** [comment]
See pull request #75

**Comment by BerkieBb** [comment]
No, just update qb-input

**Comment by Liridon69** [comment]
@BerkieBb  how can i add two jobs to open the door

**Comment by BerkieBb** [comment]
Check the readme

**Comment by Liridon69** [comment]
![Screenshot_30](https://user-images.githubusercontent.com/32654264/155304079-1eb15f41-a014-4bcd-8356-0c8cb708ef6e.png)
![Screenshot_31](https://user-images.githubusercontent.com/32654264/155304090-94cbd553-5ccc-414e-b72a-3887fb8126c6.png)
![Screenshot_32](https://user-images.githubusercontent.com/32654264/155304091-4e5854c4-5523-4974-b6fd-d7298b35b413.png)


why after i hack door its not open, is this the right way to get the id because i put 16 because 
 last one was prison door 15

**Comment by ihyajb** [comment]
@Liridon69 id be more worried about that leaked map of yours...

**Comment by Liridon69** [comment]
> @Liridon69 id be more worried about that leaked map of yours...

https://github.com/ImpulseFPS/QBCore-Bobcat-Heist idk it
